# Generated by Django 5.2.3 on 2025-07-01 01:26

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('actor', models.CharField(choices=[('advertiser', 'Я рекламодатель'), ('author', 'Я автор'), ('question', 'Я просто спросить')], max_length=20, verbose_name='Роль')),
                ('theme', models.CharField(max_length=200, validators=[django.core.validators.MinLengthValidator(5, message='Тема должна содержать минимум 5 символов'), django.core.validators.MaxLengthValidator(200, message='Тема не должна превышать 200 символов')], verbose_name='Тема')),
                ('email', models.EmailField(max_length=254, validators=[django.core.validators.EmailValidator()], verbose_name='Email')),
                ('name_company', models.CharField(blank=True, max_length=150, null=True, validators=[django.core.validators.MaxLengthValidator(150)], verbose_name='Название компании')),
                ('name_person', models.CharField(max_length=100, validators=[django.core.validators.MinLengthValidator(2, message='Имя должно содержать минимум 2 символа'), django.core.validators.MaxLengthValidator(100, message='Имя не должно превышать 100 символов')], verbose_name='Имя')),
                ('message', models.TextField(validators=[django.core.validators.MinLengthValidator(10, message='Сообщение должно содержать минимум 10 символов'), django.core.validators.MaxLengthValidator(2000, message='Сообщение не должно превышать 2000 символов')], verbose_name='Сообщение')),
                ('status', models.CharField(choices=[('new', 'Новое'), ('completed', 'Выполнено'), ('rejected', 'Отклонено')], default='new', max_length=20, verbose_name='Статус')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='IP адрес')),
                ('user_agent', models.TextField(blank=True, null=True, verbose_name='User Agent')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
            ],
            options={
                'verbose_name': 'Обратная связь',
                'verbose_name_plural': 'Обратная связь',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['status', 'created_at'], name='feedback_fe_status_91deca_idx'), models.Index(fields=['email'], name='feedback_fe_email_ac3dcf_idx'), models.Index(fields=['actor'], name='feedback_fe_actor_e2fed4_idx')],
            },
        ),
    ]
